import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import Link from "next/link"
import { Music, CheckCircle } from "lucide-react"

export default function SoundHealingPage() {
  const benefits = [
    "Manages stress and anxiety effectively",
    "Improves focus and concentration",
    "Releases physical tension and blockages",
    "Clears energetic blockages",
    "Promotes deep relaxation",
    "Works at a cellular level for overall well-being",
  ]

  return (
    <div className="min-h-screen">
      <Navigation />

      <section className="relative overflow-hidden bg-gradient-to-br from-primary/10 to-background">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div className="animate-fade-in">
              <div className="inline-flex items-center gap-2 bg-primary/10 text-primary px-4 py-2 rounded-full text-sm mb-6">
                <Music className="h-4 w-4" />
                <span>Vibrational Healing</span>
              </div>
              <h1 className="text-5xl font-bold text-foreground mb-6">Sound Healing</h1>
              <p className="text-xl text-muted-foreground mb-8 leading-relaxed">
                Experience the therapeutic power of sound frequencies to restore harmony, balance, and healing
                throughout your entire being.
              </p>
              <Button asChild size="lg" className="bg-primary text-primary-foreground hover:bg-primary/90">
                <Link href="/contact">Book a Sound Healing Session</Link>
              </Button>
            </div>
            <div className="relative animate-fade-in-delay-1">
              <div className="aspect-[4/3] rounded-2xl overflow-hidden">
                <img
                  src="/sound-healing-singing-bowls-peaceful-therapy.jpg"
                  alt="Sound Healing"
                  className="w-full h-full object-cover"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-4xl font-bold text-foreground mb-6 animate-fade-in">What is Sound?</h2>
          <div className="prose prose-lg max-w-none space-y-4 animate-fade-in-delay-1">
            <p className="text-muted-foreground leading-relaxed">
              Sound is a fundamental form of energy that travels through various mediums such as air, water, or solids
              in wave patterns. These waves are generated by vibrations, which cause oscillations in the particles of
              the medium, allowing the energy to propagate. When an object vibrates, it produces a ripple effect,
              transferring energy to the surrounding particles.
            </p>
          </div>
        </div>
      </section>

      <section className="bg-secondary/30 py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div className="animate-slide-in-left">
              <h2 className="text-4xl font-bold text-foreground mb-6">The Unique Sound of Singing Bowls</h2>
              <div className="space-y-4">
                <p className="text-muted-foreground leading-relaxed">
                  Singing bowls, commonly used in sound healing, are meticulously crafted to produce precise therapeutic
                  vibrations. The healing power of sound lies in its ability to resonate with the body's natural
                  frequencies.
                </p>
                <p className="text-muted-foreground leading-relaxed">
                  When sound waves from singing bowls enter the body, they create gentle vibrations that travel through
                  tissues, muscles, bones, and organs. These vibrations help release physical tension, clear energetic
                  blockages, and promote deep relaxation.
                </p>
                <p className="text-muted-foreground leading-relaxed">
                  Sound vibrations also activate the somatosensory system, which processes sensations from the skin,
                  muscles, and internal organs. For instance, when a singing bowl is placed on the back, its vibrations
                  are transmitted as neural impulses to specific regions of the brain.
                </p>
                <p className="text-muted-foreground leading-relaxed">
                  This form of healing is effective in managing stress, anxiety, improving focus and concentration, and
                  works at a cellular level to support overall well-being.
                </p>
              </div>
            </div>
            <div className="relative animate-slide-in-right">
              <div className="aspect-square rounded-2xl overflow-hidden">
                <img
                  src="/singing-bowl-golden-therapeutic-healing-vibrations.jpg"
                  alt="Singing Bowl"
                  className="w-full h-full object-cover"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="text-center mb-12 animate-fade-in">
          <h2 className="text-4xl font-bold text-foreground mb-4">Benefits of Sound Healing</h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">Harmonize your body, mind, and spirit</p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {benefits.map((benefit, index) => (
            <Card
              key={benefit}
              className="p-6 border-border animate-fade-in-delay-1 hover:scale-105 transition-transform duration-300"
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              <div className="flex items-start gap-3">
                <CheckCircle className="h-6 w-6 text-primary flex-shrink-0 mt-1" />
                <p className="text-foreground leading-relaxed">{benefit}</p>
              </div>
            </Card>
          ))}
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="bg-gradient-to-br from-primary/20 to-accent/20 rounded-2xl p-12 text-center animate-fade-in">
          <h2 className="text-4xl font-bold text-foreground mb-4">Experience Sound Meditation with Universal Bowl</h2>
          <p className="text-lg text-muted-foreground mb-8 max-w-2xl mx-auto">
            Immerse yourself in healing vibrations and restore your natural harmony.
          </p>
          <p className="text-sm text-muted-foreground mb-8 italic">
            Please note each individual's experience and results may vary for different individuals.
          </p>
          <Button asChild size="lg" className="bg-primary text-primary-foreground hover:bg-primary/90">
            <Link href="/contact">Book Your Session</Link>
          </Button>
        </div>
      </section>

      <Footer />
    </div>
  )
}
